version: '3.9'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - ./some_tokens.sql:/docker-entrypoint-initdb.d/some_tokens.sql

  pgadmin:
    image: adminer:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'test@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'test'
    ports:
      - '8082:8080'
    depends_on:
      - postgres