export enum ServiceError {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  USER_EXIST = 'USER_EXIST',
  INVALID_REFRESH_TOKEN_INVALID = 'INVALID_REFRESH_TOKEN_INVALID',
}
